### ISSUE TITLE
compile error with too many arguments

### ISSUE THREAD

**Issue by funkyshoc** [RafaGago/mini-async-log#17]
I get a nice compiler error in one case where I exceed 14 arguments.  It is nice that it catches the problem on compile time in that case.  However if I do want to exceed 14 arguments, is there a define or some config option I can set to allow additional arguments?

**Comment by RafaGago** [comment]
This is because the code was written to be compatible with Visual Studio 2010 and I thought that 14 parameters were enough for most needs.

To solve it variadic templates detection and a variadic template implementation needs to be implemented.

https://github.com/RafaGago/mini-async-log/blob/master/include/mal_log/mal_interface.hpp#L67

**Comment by RafaGago** [comment]
PR's are welcome

**Comment by funkyshoc** [comment]
May do a modify and check in but that restriction is fine for now.
