### ISSUE TITLE
Compile time format string checker failing in g++ amd64 compilers.

### ISSUE THREAD

**Issue by RafaGago** [RafaGago/mini-async-log#6]
I don't remember exactly which compiler version is, it's the one bundled in Ubuntu 14.10 amd64.

**Comment by holenaj** [comment]
Hi Rafa,

I found a similar error using gcc 4.8.5 (the version bundled with CentOS 7). Not sure if it's the same cause as you're seeing in Ubuntu 14.10 amd64, but for me the fix was to change some 1s that were being left-shifted to 1UL, as per the attached diff.

Hope this is helpful, and thanks for the great library!

John
[gdiff.txt](https://github.com/RafaGago/mini-async-log/files/224945/gdiff.txt)

**Comment by RafaGago** [comment]
Good catch! 

I pushed the fix to the master branch.

Thanks for reporting.
